import {
	Activity,
	ArchiveRestore,
	ArrowRight,
	Ban,
	BanknoteArrowDown,
	BanknoteArrowUp,
	BookText,
	Building2,
	Calendar,
	Car,
	CarFront,
	Check,
	ChevronLeft,
	CircleAlert,
	CircleCheck,
	CircleEllipsis,
	CircleSlash,
	CircleUser,
	CircleX,
	ClipboardClock,
	Clock,
	ClockFading,
	ClockPlus,
	Code,
	Coins,
	CornerRightDown,
	Cuboid,
	Ellipsis,
	Eraser,
	Expand,
	Eye,
	EyeOff,
	FileCog,
	FilePenLine,
	FileSignal,
	FileStack,
	FileText,
	GalleryVerticalEnd,
	Hammer,
	HardDrive,
	IdCard,
	Info,
	KeyRound,
	LayoutTemplate,
	ListStart,
	Loader,
	Lock,
	LockKeyhole,
	LogIn,
	type LucideProps,
	Mail,
	MailCheck,
	Mails,
	MapPin,
	MapPinHouse,
	Minus,
	PiggyBank,
	Play,
	Plus,
	RefreshCcw,
	Route,
	Save,
	Search,
	Settings,
	Settings2,
	Share2,
	Shield,
	ShieldUser,
	SquareParkingOff,
	SquarePen,
	TableOfContents,
	Tag,
	TextSearch,
	ThumbsUp,
	TicketCheck,
	Timer,
	Trash2,
	TrendingUp,
	TriangleAlert,
	Undo2,
	UserRound,
	Users,
	Wrench,
	X,
} from 'lucide-react';
import type React from 'react';
import { capitalizeFirstLetter } from '@/helpers/string.helper';

const createIcon = (IconComponent: React.ComponentType<LucideProps>) => {
	return ({ size = 16, ...props }: LucideProps) => (
		<IconComponent size={size} {...props} />
	);
};

export const Icons = {
	Search: createIcon(Search),
	Visible: createIcon(Eye),
	Obscured: createIcon(EyeOff),
	Info: createIcon(Info),
	Clear: createIcon(Eraser),
	Minimize: createIcon(Minus),
	Close: createIcon(X),
	Expand: createIcon(Expand),
	More: createIcon(Ellipsis),
	LessLeft: createIcon(ChevronLeft),
	TextSearch: createIcon(TextSearch),

	Email: createIcon(Mail),
	Password: createIcon(KeyRound),
	Tag: createIcon(Tag),
	Calendar: createIcon(Calendar),
	Settings: createIcon(Settings),
	Security: createIcon(Shield),
	Sessions: createIcon(FileStack),
	User: createIcon(UserRound),
	Users: createIcon(Users),
	HardDrive: createIcon(HardDrive),
	History: createIcon(ClipboardClock),
	Cron: createIcon(GalleryVerticalEnd),
	List: createIcon(ListStart),
	Mails: createIcon(Mails),
	Template: createIcon(LayoutTemplate),
	Logs: createIcon(TableOfContents),
	Account: createIcon(CircleUser),
	Permission: createIcon(Wrench),
	Content: createIcon(FileStack),
	Location: createIcon(MapPin),
	CashFlow: createIcon(PiggyBank),
	OperationalRecord: createIcon(BanknoteArrowUp),
	Financial: createIcon(BookText),
	Client: createIcon(IdCard),
	Address: createIcon(MapPinHouse),
	Brand: createIcon(FileSignal),
	City: createIcon(Building2),
	Code: createIcon(Code),
	Activity: createIcon(Activity),
	Asset: createIcon(Settings2),
	Vehicle: createIcon(Car),
	CompanyVehicle: createIcon(CarFront),
	Clock: createIcon(Clock),
	WorkSession: createIcon(Timer),
	Cmr: createIcon(FileText),
	CmrSession: createIcon(ShieldUser),
	Payment: createIcon(Coins),
	MapPin: createIcon(MapPin),
	Share: createIcon(Share2),

	ArrowRight: createIcon(ArrowRight),
	ArrowCurvedBottom: createIcon(CornerRightDown),

	Status: {
		Active: createIcon(CircleCheck),
		Pending: createIcon(Clock),
		Inactive: createIcon(CircleSlash),
		Deleted: createIcon(Ban),
		Ok: createIcon(ThumbsUp),
		Error: createIcon(CircleAlert),
		Warning: createIcon(TriangleAlert),
		Sent: createIcon(MailCheck),
		Success: createIcon(CircleCheck),
		Loading: createIcon(Loader),

		Authorized: createIcon(CircleCheck),
		Completed: createIcon(Check),
		Failed: createIcon(CircleAlert),
		Canceled: createIcon(CircleX),
		Expired: createIcon(ClockFading),
		RequiresAction: createIcon(TriangleAlert),

		Verified: createIcon(Check),
		Draft: createIcon(FilePenLine),

		InUse: createIcon(Car),
		Damaged: createIcon(Hammer),
		Sold: createIcon(BanknoteArrowUp),
		Scrapped: createIcon(SquareParkingOff),
		Closed: createIcon(Lock),
		Assigned: createIcon(TicketCheck),
		Returned: createIcon(Undo2),

		Ordered: createIcon(Play),
		Preparing: createIcon(CircleEllipsis),
		Transit: createIcon(Route),
		Delivered: createIcon(Cuboid),
		Delayed: createIcon(ClockPlus),
	},
	Action: {
		Save: createIcon(Save),
		Submit: createIcon(Play),
		Login: createIcon(LogIn),
		Create: createIcon(Plus),
		Add: createIcon(Plus),
		Update: createIcon(SquarePen),
		Delete: createIcon(Trash2),
		Cancel: createIcon(X),
		Destroy: createIcon(CircleX),
		Reset: createIcon(RefreshCcw),
		Enable: createIcon(CircleCheck),
		Disable: createIcon(LockKeyhole),
		Restore: createIcon(ArchiveRestore),
		Permissions: createIcon(Wrench),
		View: createIcon(Eye),
		Complete: createIcon(Check),
		Drop: createIcon(CircleX),
		Refund: createIcon(BanknoteArrowDown),
		Verified: createIcon(Check),
		Draft: createIcon(FilePenLine),
		StatusTransition: createIcon(TrendingUp),
		Close: createIcon(Lock),
		Setup: createIcon(FileCog),
		Return: createIcon(Undo2),
	},
};

export function getActionIcon(action: string) {
	action = capitalizeFirstLetter(action);

	if (action in Icons.Action) {
		return Icons.Action[action as keyof typeof Icons.Action];
	}

	throw new Error(`${action} is not defined in Icons.Action`);
}
